; ((a b (c d) e))
(setf a 'a)
(setf b 'b)
(setf c 'c)
(setf d 'd)
(setf e 'e)
; (cons (cons a (cons b (cons c ))) nil)
(write (cons (cons (cons (cons (cons c (cons d nil)) nil) nil) (cons b nil))))
(cons (cons 'b nil) (cons 'c nil))